In [1]:
import pandas as pd

df = pd.read_csv("../data.csv")

# Analyser les données

Maintenant nous allons pouvoir faire parler les données. On utilise la méthode **`describe()`** qui affiche un **tableau récapitulatif** avec des statistiques descriptives (moyenne, min, max, écart-type, etc.).

In [2]:
df.describe()

                id    tax
count  1000.000000  654.0
mean    500.500000   20.0
std     288.819436    0.0
min       1.000000   20.0
25%     250.750000   20.0
50%     500.500000   20.0
75%     750.250000   20.0
max    1000.000000   20.0

In [3]:
df["price_paid"].describe()

count      1000
unique      528
top       $3.73
freq          8
Name: price_paid, dtype: object

## Moyenne avec `mean()`

Nous pouvons récupérer la **moyenne** d'une colonne grâce à **`mean()`**.

> Ne pas oublier de faire une **conversion** si nécessaire (ex. : `str` → `float`).

In [2]:

# mettre les valeurs manquantes à 0
df["tax"] = df["tax"].fillna(0)

# convertir les valeurs de la colonne "price_paid" en float
df["price_paid"] = df["price_paid"].apply(lambda x: x.replace("$", ""))
df["price_paid"] = df["price_paid"].astype(float)

df["price_paid"].mean()

np.float64(6.461930000000001)

## Somme avec `sum()`

On peut obtenir le **total** d'une colonne numérique avec **`sum()`**.

In [25]:
df["price_paid"].sum()

6461.93

## Minimum et Maximum

On retrouve la **valeur minimum** et la **valeur maximum** d'une colonne avec **`min()`** et **`max()`**.

In [6]:
df["price_paid"].min()

np.float64(3.0)

In [7]:
df["price_paid"].max()

np.float64(10.0)

## Valeurs uniques avec `unique()`

Pour récupérer les **valeurs uniques** d'une colonne, on utilise **`unique()`**.

In [ ]:
df["country"].unique()

### Conversion en liste avec `tolist()`

On peut convertir le résultat en **liste Python** avec **`tolist()`**.

In [ ]:
df["price_paid"].unique().tolist()

## Compter les occurrences avec `value_counts()`

**`value_counts()`** renvoie le **nombre d'occurrences** de chaque valeur dans une colonne. On peut aussi passer `normalize=True` pour obtenir les **proportions**.

In [ ]:
df["country"].value_counts()

In [26]:
df["gender"].value_counts()

# ou 

df["gender"].value_counts(normalize=True)

gender
Female    0.529538
Male      0.470462
Name: proportion, dtype: float64

## Regrouper avec `groupby()`

Pour **regrouper** des éléments selon une colonne, on utilise **`groupby()`**.

In [9]:
# ne peut pas etre utilisé comme ceci 
x =list(df.groupby("country"))
x

[('Canada',
         id        date first_name   last_name                      email  \
  0       1  03/28/2021    Marylin      Alders       malders0@shop-pro.jp
  1       2  03/19/2021      Hinda    Harridge         hharridge1@gnu.org
  6       7  03/14/2021        Ava     Kencott         akencott6@phoca.cz
  8       9  03/09/2021     Waylon    Heersema      wheersema8@tumblr.com
  10     11  03/11/2021       Lief   Woodcraft  lwoodcrafta@sitemeter.com
  ..    ...         ...        ...         ...                        ...
  964   965  03/16/2021    Marilyn   McKiernan       mmckiernanqs@mapy.cz
  969   970  03/15/2021       Dody  Jakubovics    djakubovicsqx@ifeng.com
  971   972  03/09/2021      Devan      Kamena          dkamenaqz@umn.edu
  978   979  03/18/2021  Bartolemo     Veelers      bveelersr6@smh.com.au
  999  1000  03/23/2021   Rochelle    Pringuer      rpringuerrr@house.gov

       gender       ip_address country  price_paid   tax
  0      Male    160.119.8.119  Canada        5.36   0.0
  1    Female   210.51.172.132  Canada        8.32   0.0
  6    Female    118.251.45.43  Canada        6.29   0.0
  8      Male   63.242.174.112  Canada        3.70  20.0
  10     Male    201.76.240.51  Canada        5.71   0.0
  ..      ...              ...     ...         ...   ...
  964    Male   50.243.237.247  Canada        4.23  20.0
  969  Female     0.217.109.79  Canada        4.36   0.0
  971  Female    7.228.190.130  Canada        7.25  20.0
  978    Male  149.150.196.237  Canada        7.76  20.0
  999     NaN   170.193.249.83  Canada        8.01  20.0

  [161 rows x 10 columns]),
 ('France',
        id        date first_name   last_name                       email  \
  7      8  03/08/2021       Codi     Feasley            cfeasley7@ed.gov
  9     10  03/23/2021  Guglielma      Gookes       ggookes9@amazon.co.uk
  13    14  03/24/2021       Cull      Vassie          cvassied@unblog.fr
  18    19  03/16/2021      Judye       Behan           jbehani@google.es
  20    21  03/12/2021    Jeffrey     Stanman       jstanmank@latimes.com
  ..   ...         ...        ...         ...                         ...
  990  991  03/19/2021       Shep    Thorburn  sthorburnri@prnewswire.com
  992  993  03/04/2021    Maurene  Guilloneau      mguilloneaurk@about.me
  993  994  03/22/2021      Ossie      Snelle            osnellerl@nhs.uk
  994  995  03/17/2021   Carolyne    Bruntjen   cbruntjenrm@reference.com
  995  996  03/24/2021       Duff      Errigo        derrigorn@elpais.com

       gender      ip_address country  price_paid   tax
  7      Male  26.190.191.249  France        3.01  20.0
  9      Male     169.100.6.0  France        9.05   0.0
  13      NaN    18.203.61.94  France        5.97  20.0
  18   Female     27.196.2.18  France        4.90  20.0
  20   Female    3.110.64.192  France        5.55  20.0
  ..      ...             ...     ...         ...   ...
  990    Male  108.123.252.15  France        7.02  20.0
  992    Male  108.73.141.204  France        9.19   0.0
  993    Male  230.187.67.246  France        4.31   0.0
  994  Female     7.29.168.78  France        5.68  20.0
  995  Female  193.84.247.144  France        3.63   0.0

  [408 rows x 10 columns]),
 ('Morocco',
        id        date   first_name    last_name                          email  \
  4      5  03/24/2021        Kanya      Beasant            kbeasant4@jigsy.com
  30    31  03/28/2021        Tommi    Ditchburn          tditchburnu@bbc.co.uk
  42    43  03/22/2021        Tonia     Jacqueme    tjacqueme16@hugedomains.com
  75    76  03/28/2021     Penelope        Brood        pbrood23@macromedia.com
  88    89  03/21/2021        Randy        Tiebe       rtiebe2g@livejournal.com
  104  105  03/07/2021          Lay     Bouchier       lbouchier2w@multiply.com
  119  120  03/25/2021      Kristal       Kettel              kkettel3b@nps.gov
  158  159  03/07/2021      Ethelin         Gors      egors4e@blogtalkradio.com
  168  169  03/01/2021       Willis  Sandercroft         wsandercroft4o@loc.gov
  191  192  03/24/2021     Ninnette      McGruar             nmcgruar5b@ihg.com
  195  196  03/22/2021    Frederica   Stuchburie        fstuchburie5f@ocn.ne.jp
  205  206  03/29/2021       Kendal      Huleatt      khuleatt5p@shutterfly.com
  289  290  03/15/2021       Wandis   MacCoughen     wmaccoughen81@so-net.ne.jp
  301  302  03/22/2021        Ollie    Suermeier   osuermeier8d@istockphoto.com
  304  305  03/11/2021      Rodrick       Gierek      rgierek8g@kickstarter.com
  316  317  03/28/2021       Duncan      Dymocke         ddymocke8s@archive.org
  337  338  03/14/2021     Carolyne   Eschalette    ceschalette9d@wordpress.com
  349  350  03/20/2021         Elsi       Pieper          epieper9p@jiathis.com
  362  363  03/22/2021       Mureil       Bartke   mbartkea2@simplemachines.org
  375  376  03/14/2021      Abagael     Lafflina          alafflinaaf@prlog.org
  379  380  03/21/2021     Sheelagh      Gilmore            sgilmoreaj@bing.com
  386  387  03/12/2021        Jayme     Giottini             jgiottiniaq@cbc.ca
  398  399  03/26/2021    Giulietta          Hun                 ghunb2@tiny.cc
  407  408  03/28/2021        Lanie     Slidders            lsliddersbb@aol.com
  445  446  03/05/2021           Ag       Dwelly                adwellycd@ow.ly
  451  452  03/18/2021      Maritsa    Spratling        mspratlingcj@netlog.com
  499  500  03/21/2021      Orlando      Becaris           obecarisdv@chron.com
  532  533  03/17/2021     Rosamund      Pawlick           rpawlickes@about.com
  537  538  03/08/2021     Alphonso     Fayerman   afayermanex@businesswire.com
  541  542  03/07/2021         Tera    Hartridge     thartridgef1@clickbank.net
  551  552  03/18/2021       Sherie        Jermy           sjermyfb@foxnews.com
  581  582  03/19/2021      Maureen        Crick            mcrickg5@abc.net.au
  598  599  03/23/2021      Sibilla       Monday          smondaygm@plala.or.jp
  600  601  03/19/2021         Lusa     McColgan         lmccolgango@nature.com
  606  607  03/19/2021         Arda         Yude        ayudegu@dailymail.co.uk
  621  622  03/04/2021         Esme   Jodlkowski        ejodlkowskih9@zdnet.com
  627  628  03/13/2021         Saul        Resun       sresunhf@list-manage.com
  645  646  03/08/2021         Judy       Chuney              jchuneyhx@mlb.com
  648  649  03/10/2021    Theresina    Constable        tconstablei0@usnews.com
  659  660  03/21/2021        Levon        Jaine             ljaineib@google.ru
  681  682  03/02/2021        Clare     Breitler  cbreitlerix@printfriendly.com
  721  722  03/02/2021      Jerrine     Stollman          jstollmank1@google.it
  736  737  03/15/2021  Constantine        Loble              cloblekg@digg.com
  762  763  03/01/2021       Truman    Dunbobbin        tdunbobbinl6@weebly.com
  789  790  03/09/2021        Elnar    Hurleston    ehurlestonlx@slideshare.net
  791  792  03/11/2021       Faythe      Lofting         floftinglz@mozilla.com
  835  836  03/05/2021           Hy     Jeschner            hjeschnern7@irs.gov
  872  873  03/13/2021     Theodora        Croux                tcrouxo8@a8.net
  882  883  03/03/2021        Aluin     Petegrew        apetegrewoi@alibaba.com
  891  892  03/29/2021      Vincenz      Torrisi         vtorrisior@weather.com
  903  904  03/02/2021    Doralynne         Kime          dkimep3@amazonaws.com
  977  978  03/14/2021       Bronny      Kemball      bkemballr5@thetimes.co.uk
  983  984  03/03/2021      Rhianon      McGrale             rmcgralerb@wix.com
  991  992  03/07/2021        Elihu        Crush          ecrushrj@berkeley.edu

       gender       ip_address  country  price_paid   tax
  4      Male  106.252.162.233  Morocco        9.24  20.0
  30   Female      8.92.173.38  Morocco        7.81  20.0
  42     Male   65.151.183.165  Morocco        5.29  20.0
  75     Male    223.231.69.66  Morocco        6.39   0.0
  88   Female      98.223.40.3  Morocco        4.95  20.0
  104    Male    219.90.36.188  Morocco        4.32  20.0
  119     NaN    151.36.18.192  Morocco        9.47  20.0
  158  Female    49.70.235.121  Morocco        7.98  20.0
  168  Female    63.189.92.203  Morocco       10.00  20.0
  191    Male   170.97.155.166  Morocco        9.60  20.0
  195  Female     46.120.92.17  Morocco        9.51   0.0
  205  Female  232.135.221.184  Morocco        5.82  20.0
  289    Male    85.203.29.182  Morocco        9.13  20.0
  301  Female     163.77.66.47  Morocco        9.98   0.0
  304    Male    24.127.196.24  Morocco        8.27   0.0
  316  Female    131.184.17.89  Morocco        5.83  20.0
  337    Male   137.166.201.65  Morocco        9.04  20.0
  349    Male   158.232.177.99  Morocco        4.23   0.0
  362  Female   136.214.48.211  Morocco        7.93  20.0
  375  Female    60.155.75.228  Morocco        6.50  20.0
  379  Female    101.59.14.157  Morocco        8.17  20.0
  386  Female   91.206.101.226  Morocco        3.34  20.0
  398  Female     82.47.217.54  Morocco        9.96  20.0
  407    Male    11.219.12.121  Morocco        4.42   0.0
  445  Female      181.12.97.4  Morocco        4.10  20.0
  451    Male     96.17.174.67  Morocco        3.49   0.0
  499    Male   148.172.146.11  Morocco        6.31   0.0
  532  Female     26.33.30.214  Morocco        5.65  20.0
  537     NaN     61.182.20.63  Morocco        9.08  20.0
  541    Male    152.115.40.40  Morocco        3.73  20.0
  551  Female     48.114.5.248  Morocco        5.91  20.0
  581    Male   52.252.160.131  Morocco        7.66   0.0
  598  Female     102.95.58.85  Morocco        5.81  20.0
  600  Female   141.132.71.145  Morocco        5.98  20.0
  606  Female   255.240.144.60  Morocco        6.18  20.0
  621  Female     27.113.83.72  Morocco        9.72   0.0
  627    Male    43.120.28.189  Morocco        7.39   0.0
  645    Male  249.123.211.251  Morocco        8.96  20.0
  648    Male      247.1.89.27  Morocco        4.70  20.0
  659    Male   128.37.117.141  Morocco        4.92   0.0
  681  Female   53.157.180.213  Morocco        9.33  20.0
  721    Male  102.215.137.204  Morocco        3.06  20.0
  736  Female       9.57.195.1  Morocco        8.44  20.0
  762    Male     4.98.254.111  Morocco        8.22  20.0
  789  Female   233.99.164.115  Morocco        4.27  20.0
  791  Female   16.218.126.181  Morocco        5.62  20.0
  835  Female   171.104.13.250  Morocco        8.53  20.0
  872     NaN  168.185.141.171  Morocco        9.05   0.0
  882  Female    161.49.144.43  Morocco        3.50   0.0
  891    Male  185.200.182.118  Morocco        3.50  20.0
  903  Female     72.171.1.100  Morocco        8.85  20.0
  977     NaN    64.241.43.138  Morocco        4.32   0.0
  983    Male   37.231.252.243  Morocco        4.46  20.0
  991    Male    174.38.173.53  Morocco        5.05  20.0  ),
 ('United States',
        id        date first_name   last_name                       email  \
  2      3  03/17/2021        Erl  Kilminster       ekilminster2@etsy.com
  3      4  03/19/2021      Grata      Brantl            gbrantl3@umn.edu
  5      6  03/25/2021      Titos  Braybrooke        tbraybrooke5@umn.edu
  11    12  03/16/2021     Bailie       Wyman            bwymanb@lulu.com
  14    15  03/21/2021     Oralie      Maryon             omaryone@va.gov
  ..   ...         ...        ...         ...                         ...
  986  987  03/05/2021      Dukey     Espinal  despinalre@accuweather.com
  987  988  03/13/2021    Patrice        Barr           pbarrrf@google.de
  988  989  03/07/2021       Yves      Botler  ybotlerrg@miitbeian.gov.cn
  997  998  03/13/2021      Betty    Stickels  bstickelsrp@cloudflare.com
  998  999  03/17/2021    Paquito       Tesoe      ptesoerq@rakuten.co.jp

       gender      ip_address        country  price_paid   tax
  2      Male   213.8.101.145  United States        3.73  20.0
  3    Female   5.140.237.101  United States        3.70  20.0
  5    Female  173.100.21.179  United States        5.82   0.0
  11     Male  222.60.138.222  United States        3.15  20.0
  14   Female  215.248.16.198  United States        4.53  20.0
  ..      ...             ...            ...         ...   ...
  986    Male   30.61.204.231  United States        4.07  20.0
  987    Male  14.129.223.239  United States        6.20  20.0
  988  Female  148.191.87.121  United States        6.10  20.0
  997    Male    199.80.60.87  United States        7.54  20.0
  998    Male     0.183.63.11  United States        5.81   0.0

  [333 rows x 10 columns])]

In [27]:
#df.groupby("country").sum()

df.groupby("country").sum(numeric_only=True)

                   id  price_paid     tax
country
Canada          70365     1017.45  2160.0
France         214440     2619.61  5100.0
Morocco         26591      362.97   780.0
United States  168150     2183.67  4520.0

In [28]:
df.groupby("country")["price_paid"].sum()

country
Canada           1017.45
France           2619.61
Morocco           362.97
United States    2183.67
Name: price_paid, dtype: float64